name: Build & push

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "¡Hola Mundo!"
