name: Build & push

on:
  push:
    branches:
      - main

  workflow_dispatch:

  pull-request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Hola Mundo
        run: echo "¡Hola Mundo!"
